### PR TITLE
Adding the system_ini template

### PR DESCRIPTION
**Pull request by jmauro**
Hey Noah,

Instead of using the generic _systemd_ template, sometime you wish to add more directives, one way to do it would be to use attributes to generate the _systemd_ script.

I create a PR in that sense let me know if you think that is worth adding it to `poise-service`

Regards,
JM

### CODE REVIEW

**Comment by coderanger** [comment]
General idea is good, but I would want to grab the ini generator code from poise-supervisor probably because that handles funky escaping a bit better.

**Comment by jmauro** [comment]
Cool, you want to summit a new PR? If so, could you point me to the pattern you want me to use, because I have no idea of you are talking about.

Thx

**Comment by jorisd** [comment]
@jmauro I think he asks you to check poise-supervisor 's code to generate INI files : 
https://github.com/poise/poise-supervisor/blob/master/lib/poise_supervisor/utils/ini.rb

**Comment by jmauro** [comment]
Any love to this PR?

**Comment by coderanger** [comment]
You didn't write any tests, which is notable because it wouldn't actually pass any of those tests.

**Comment by jmauro** [comment]
Hey @coderanger , tell me exactly what requirement you want for the patch and I would be glad to do them as loong as you explain where I can find some documentation. I am not a dev so some part part of poise is not that obvious for me so don't hesitate to be explicit :smile: 

thx

**Comment by jmauro** [comment]
Hey @coderanger,

Tell me if that's enough? If not, please give me some pointers.

By the way, you should definitely put some documentation regarding contribution to the poise-service framework, because I was struggling to try to understand the pattern to use and the directory structure.

Regards,
JM

**Comment by coderanger** [comment]
@jmauro I'm just one person, it will take some time before I circle back to this. As it stands this is not a viable user experience. Setting ini-level options shouldn't require a change to the template name as a default flow. I'll take care of this when I merge it, but it will be a bit until I've got the cycles for it.

**Comment by jmauro** [comment]
Ok, thanks @coderanger .
Since we are pushing internally to use `poise-service` for upgrading to CentOS 7 smoothly, I might be a too pushy, sorry.

Regards,
JM

**Comment by coderanger** [comment]
You can do this externally pretty easily, don't need to wait on me :)

**Comment by jmauro** [comment]
Any love about this PR?

**Comment by coderanger** [comment]
It will take a fair bit of reworking before it could be merged, but because provider options already exist to swap out the template, this is low-priority work.

**Comment by coderanger** [comment]
Upon further reflection I think this probably doesn't need to be in posie-service itself. There are powerful systems in place for replacing the template already, and I don't think it's super important to allow generating the INI from Ruby data structures as most unit files aren't that complex. The main use case around improved template overrides is how to allow overriding just part of the template without fully copying it, but this patch/feature doesn't really address that as you would have to copy the whole Ruby data structure. I think a better approach is to look at using partial templates.

**Pull request closed without merging**
