### PR TITLE
Fix issue with Berkshelf complaining when uploading to Chef Server.

### PR DESCRIPTION
**Pull request by johnbellone**
```sh
n=12.0.0;oc_erchef=1.6.4"}, status=400>
D, [2015-05-28T14:26:08.227646 #24211] DEBUG -- : ** error encounted in Chef response
E, [2015-05-28T14:26:08.290630 #24211] ERROR -- : Ridley::Errors::HTTPBadRequest: {"error":["Invalid element in array 
value of 'templates'."]}
E, [2015-05-28T14:26:08.290799 #24211] ERROR -- : /home/jbellone/.gem/ruby/2.2.1/gems/ridley-4.1.2/lib/ridley/middlewa
re/chef_response.rb:24:in `on_complete'
```

### CODE REVIEW

**Comment by johnbellone** [comment]
I am wondering if #3 is related to me adding a default directory here to fix this upload.

**Comment by coderanger** [comment]
Upstream issue tracked in https://github.com/chef/chef-server/pull/318 but it will be a while before I'll be able to revert this. Sighhhhhh.

**Comment by coderanger** [comment]
Berks side of the fix is tracked on https://github.com/reset/ridley/pull/309, could potentially revert this when that fix is in a Berks release and/or ChefDK release.

**Comment by johnbellone** [comment]
This is a nasty one!

**Comment by alainchiasson** [comment]
Will this be pushed to supermarket ? as 1.0.2

**Comment by coderanger** [comment]
@alainchiasson The fix was released on the berks side shortly after this was closed, so there was no need.

**Comment by alainchiasson** [comment]
Thanks @coderanger . I updated to the latest chefdk (0.6.0 -> 0.6.2). Things worked afterwards. Odd thing is the berks was still the same version ( 3.2.4 )

**Comment by coderanger** [comment]
The fix was technically in Ridley, the gem Berkshelf uses for Chef API stuffs.

**Pull request merged**
